// gen_symdefs.mjs — 常駐イメージ(.noi)の全globalシンボルを「絶対番地の .s」に落とす。
//   バンクモジュール(冷たいシーン)は常駐関数/globalを直接呼べないと不便なので、
//   常駐を先にリンク→本ツールでシンボル番地を抽出→バンク側リンクに食わせて解決する。
//   除外: 0xA000-0xBFFF(スワップ窓=バンク自身の領域。ここは各バンクが自前で持つ)。
// 使い方: node tools/gen_symdefs.mjs build/rom.noi build/resident_syms.s
import { readFileSync, writeFileSync } from 'node:fs';

const [, , inNoi, outS] = process.argv;
if (!inNoi || !outS) { console.error('usage: node tools/gen_symdefs.mjs <rom.noi> <out.s>'); process.exit(2); }

let out = ';; auto-generated by tools/gen_symdefs.mjs — 常駐シンボルの絶対番地\n';
out += ';; バンクモジュールから常駐関数/globalを呼ぶために link する。編集しないこと。\n';
out += '\t.module resident_syms\n';

let n = 0;
for (const line of readFileSync(inNoi, 'utf8').split(/\r?\n/)) {
  const m = line.match(/^DEF\s+(_\w+)\s+0x([0-9A-Fa-f]+)\s*$/);
  if (!m) continue;
  const sym = m[1];
  const addr = parseInt(m[2], 16);
  if (addr >= 0xA000 && addr < 0xC000) continue;   // スワップ窓は除外
  // ★sdccランタイムヘルパ(__moduchar/__divuchar/__mulint 等の二重アンダースコア)は除外。
  //   これらは各バンクが自分の lib から持つべきもので、常駐のを export すると
  //   バンク側 lib 由来と多重定義になる(ship_render の % 使用で __moduchar 衝突)。
  if (sym.startsWith('__')) continue;
  out += `\t.globl ${sym}\n${sym} = 0x${addr.toString(16)}\n`;
  n++;
}
writeFileSync(outS, out);
console.log(`resident_syms: ${n} 個の常駐シンボルを ${outS} へ`);
